"""fixing notification column

Revision ID: 41cbc0529382
Revises: 175b3ff569d2
Create Date: 2018-01-26 20:30:01.201618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41cbc0529382'
down_revision = '175b3ff569d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('payload_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'payload_json')
    # ### end Alembic commands ###
